### ISSUE TITLE
Original Buffs vanish when you disable and enable the Plugin

### ISSUE THREAD

**Issue by NevendyND** [kawaii/Moodles#1]
Like the Title says
What i did
1: Enable Tank Stance on Warrior
2: Disabled Plugin
3: Enabled Plugin

I think its not that big of a Problem because the Tank Stance is still "there" and can be deactivated via Skill.

**Comment by kawaii** [comment]
Confirmed the problem. Will be pushing out an update a bit later to resolve this and a number of other issues.

**Comment by kawaii** [comment]
Resolved in 800cbfb2decefc1298651394e87a9781c7ddacf0.
