### ISSUE TITLE
Games closes itself without Error after enabling Automation

### ISSUE THREAD

**Issue by NevendyND** [kawaii/Moodles#10]
The Games closes itself after enabling the Automation after loading the Game.
The Automation was disabled after disabling the Plugin from the Version before.
[log.txt](https://github.com/kawaii/Moodles/files/14466870/log.txt)

- It happens at the same time when the Buffs wander down. (I think the "crash" happens when they are about to hide)
![hgadrhdrh](https://github.com/kawaii/Moodles/assets/28860034/7835d372-3e19-4c76-8234-5de0d70a5b2d)

- I also tried to make a new Automation but that did the same. (It doesn't save the new created Automation after Game closes itself)
- It doesn't happen when activated in Characterpick Screen. (When it loaded it works)
- After changing my Job and another Buff gets added it closes itself again.

**Comment by NevendyND** [comment]
Update of this Situation
- I removed the old Config and remade the Buffs.
- When i activate "Normal-Preset" the Game closes itself after Freeze.
- I tried to put 3 Buffs on me and after the 4th it closes the Game.
- Here my Plugin Config: [DefaultConfig.json](https://github.com/kawaii/Moodles/files/14483615/DefaultConfig.json)

**Comment by NevendyND** [comment]
Thats the Problem, the Game closes without showing the Menu for creating a tspack file.
It freezes and then the Game is gone.

**Comment by NevendyND** [comment]
Here the Video's
**What i did**
- I tried to Alt + F4 my Game but it told me if I'm really sure that i want to close the Game.
(I showed that, that no one thinks i just Alt + F4 my Game here.)
- I clicked through the Windows and then activated the Preset, like i said it also 
- Sadly nothing in the Console.
- Video: https://github.com/kawaii/Moodles/assets/28860034/44534c8a-2e5f-475c-b7b3-3c387586f749

**Next try**
- Showed all Buffs/Debuffs removed one from Preset "Sleepy" and used it on me, Game crashed with tspack that i can send now too. (Had to zip it)

- Video: https://github.com/kawaii/Moodles/assets/28860034/233bad9d-4b40-4204-8e5c-dd5836304150
- tspack: [crash-20240304225409.zip](https://github.com/kawaii/Moodles/files/14487641/crash-20240304225409.zip)

**Last try**
- I tried to use Buffs after another and after the second or third it closed the Game
- Video: https://github.com/kawaii/Moodles/assets/28860034/33d7266a-6af5-45bc-8826-b70d73c75215

**Comment by kawaii** [comment]
I think I've figured it out. You are using the plugin EasyEyes and most likely have added the buff application VFX to your blacklist. Moodles is crashing because it's attempting to remove VFX that never existed in the first place.

**Comment by NevendyND** [comment]
That makes alot of sense yeah.

Here a List of my EasyEyes Blocked VFX's for Document.
- List: [exported_vfx.txt](https://github.com/kawaii/Moodles/files/14487986/exported_vfx.txt)

**Comment by kawaii** [comment]
Mystery solved then. Solutions are either to unblacklist these specific VFX or disable VFX in Moodles, in the settings tab.
![image](https://github.com/kawaii/Moodles/assets/12242877/40923927-c7ce-4831-a5fb-e1d7dd447e65)
