### ISSUE TITLE
Unable to apply Moodles to others you're synced with... randomly.

### ISSUE THREAD

**Issue by Schwegg** [kawaii/Moodles#15]
Some mare synced friends I am able to apply Moodles to, others I'm unable to. no errors or anything in chat, so unsure as to why this is the case.

**Comment by kawaii** [comment]
It's not intended for you to really be able to apply Moodles to people you are synced with on Mare (yet). There is a technical limitation in that Mare doesn't provide data of characters who you are synced with. So the only way I can identify them to block application is if they have some Moodles of their own already.

In the future I hope to add a whitelist system where you can add the names of characters you consent to adding Moodles to your own StatusManager, but it might require some additional work from @rootdarkarchon in order for me to fully implement it properly and fully block application of Moodles to non-consenting Mare pairs.
