### ISSUE TITLE
Import empty moodle create bug when we want to create a new statut and cause crash too

### ISSUE THREAD

**Issue by YukiaraAiko** [kawaii/Moodles#18]
I had the unpleasant surprise of importing a moodle when I did not copy an already existing moodle, so that means that the status is empty and is impossible to delete, subsequently to try to resolve the problem I I tried uninstalling the plugin and reinstalling it. Since then, every time I create a status and restart the game, the status created via the + before does not appear as if it has not been saved and the status in a preset is not displayed. And also it makes me crash the game sometimes.

![Screenshot_4](https://github.com/kawaii/Moodles/assets/96118550/8a183aba-fff0-4c8b-ba69-45a2917541c5)
![Screenshot_3](https://github.com/kawaii/Moodles/assets/96118550/7b934a29-243c-44e0-a7e4-188b67d6d525)
![Screenshot_2](https://github.com/kawaii/Moodles/assets/96118550/83e5e9c7-8af9-475b-8efb-925752b81d6f)
![Screenshot_5](https://github.com/kawaii/Moodles/assets/96118550/f4542c33-054e-4a75-9bc5-d4dc1d168f89)

**Comment by kawaii** [comment]
Can you drop your plugin config file + `dalamud.log` here please?
Everything from this folder: `%appdata%\XIVLauncher\pluginConfigs\Moodles`

**Comment by YukiaraAiko** [comment]
It's too late, I deleted the folder in it and that fixed the problem, but if you want to reproduce it, import a moodle when the clipboard is empty and that should reproduce the problem I had.

**Comment by kawaii** [comment]
Fixed in 321f2dc8d85298fc7b6bed9af5ee913bbce4ad4e.
