### ISSUE TITLE
Buffs do not display on target bar (Target info displayed Independently)

### ISSUE THREAD

**Issue by Gekkoinabox** [kawaii/Moodles#2]
The custom buffs/debuffs/special buffs do not display when the in game option, Display Target Info Independently, is enabled. They are missing from the separate  "Target Info (Status)" window.

**Comment by kawaii** [comment]
Known issue, will be resolved in an update later tonight.

**Comment by kawaii** [comment]
Fixed in 321f2dc8d85298fc7b6bed9af5ee913bbce4ad4e.
