### ISSUE TITLE
Moodles do not show up when targeting a player with controller

### ISSUE THREAD

**Issue by Sp00kems** [kawaii/Moodles#20]
Heya! I was testing some stuff with a couple friends, one of which plays on controller. We were wondering why they couldn't see moodles. So as an experiment I turned on my controller and targeted someone with the D-Pad and then bam, moodles do not appear. Even in controller mode whilst clicking on someone with the mouse the work normally.

Controller Targeted:
![image_2024-03-03_124720046](https://github.com/kawaii/Moodles/assets/161873519/267173f9-23ad-4902-9b39-71a385407276)

Mouse Targeted:
![image_2024-03-03_124757023](https://github.com/kawaii/Moodles/assets/161873519/2ccfde4b-c64e-44c4-a9f3-136186833924)

**Comment by kawaii** [comment]
Interesting. I guess targeting with a controller spawns a different kind of target HUD element instead of the usual one.
I don't own a controller so I'll have to mark this as low priority since I'm unable to test for now.

**Comment by kawaii** [comment]
@taurenkey any ideas, controller boy?

**Comment by kawaii** [comment]
Fixed by @Glyceri!
