### ISSUE TITLE
Formatting tags

### ISSUE THREAD

**Issue by oxxtazxxo** [kawaii/Moodles#22]
Not necessarily a bug, but the formatting tags. Since the description supports formatting tags, do you have an example of how it would be? Is this in HTML as well?
![ffxiv_dx11_pz3GDZq33C](https://github.com/kawaii/Moodles/assets/38712464/e0bbf550-9ac6-4594-95e0-c934e761a151)

**Comment by kawaii** [comment]
For example;
```
Hi my name is [color=red]Alyssa[/color] and I really like [glow=yellow]cats[/glow].
```
