### ISSUE TITLE
Possible Crashing over Mare

### ISSUE THREAD

**Issue by Sypsoti** [kawaii/Moodles#27]
In a somewhat large syncshell I noticed I had been crashing a lot. After some testing, enabling/disabling, and seeing a few crashes happen en mass /without/ me, I've reason to believe something in Moodles is causing crashes. The little stack trace upon crashing always mentioned VFX in some manner, but I don't have anything further to narrow it down.

**Comment by kawaii** [comment]
Yeah there's an issue in that when people disconnect from Mare and get redrawn at the same time as Moodles is trying to apply the VFX to their character, the game crashes.

I'm going to push a hotfix to just force disable the VFX feature soon until I have a solution.

**Comment by kawaii** [comment]
Pushed version 1.0.0.14.
![image](https://github.com/kawaii/Moodles/assets/12242877/0ec6963a-5bfb-49d0-bd36-6d5ac5741368)
