### ISSUE TITLE
Empty

### ISSUE THREAD

**Issue by RainyDays21** [kawaii/Moodles#34]
When I open the moodles settings I have no options, it is empty and I only have the tab "moodles." Am I missing something? Or what is wrong?
 ![image](https://github.com/user-attachments/assets/ff7db71e-bff4-4cc9-a362-01feeecaba4b)

**Comment by Limiana** [comment]
could you attach logs? `%appdata%\XIVLauncher\dalamud.log`
also please confirm that `/xlbranch` is set to "release"

**Comment by RainyDays21** [comment]
xlbranch is set to release yes. I can't drop the whole log in here it is too big should I copy paste part of it? ![image](https://github.com/user-attachments/assets/a7e1fe25-6b07-4d41-b076-098cdb4592d6)

**Comment by Limiana** [comment]
DM them to me in discord if you could, (https://discord.gg/Zzrcc8kmvy or https://discord.nightmarexiv.com/), also please send me `%appdata%\XIVLauncher\pluginConfigs\Moodles\DefaultConfig.json` as well
https://wormhole.app/ if file is too large

**Comment by RainyDays21** [comment]
Thank you! I dm'd

**Comment by Cloneme5** [comment]
I'm having the same issue, would you like me to dm you as well with my json file?

**Comment by RainyDays21** [comment]
We figured out on my end that it was the plugin "no tank you" that is not compatible. If you have that you have to disable it.

**Comment by Cloneme5** [comment]
ah yea that fixed it for me too. good to know
