### ISSUE TITLE
Moodles not showing on party list

### ISSUE THREAD

**Issue by ParallelSigns** [kawaii/Moodles#37]
Hi.

So... I have a weird issue none of my friends seem to be having.
If I click someone, I can see on their general status effects their custom moodles, but on my party list when in a party with them, I can't see those same moodles anymore.

I used to see them before the shift to Dawntrail.
I have made sure I have the most up to date versions of Mare, Penumbra, Glamourer, and Moodles.

Stranger still is that my friends can still see Moodles, even mine, on their own party list.

Not sure if anyone else is experiencing my issue, but yeah. Wanted to report it just in case.

**Comment by Limiana** [comment]
Are you using jobbars or something else that modifies party list? Such plugins would not be compatible

**Comment by ParallelSigns** [comment]
> Are you using jobbars or something else that modifies party list? Such plugins would not be compatible

This did indeed seem to be it. So thank you for solving that mystery. Though I am curious now even more so. I used to use 'No Tank You' with Moodles before the Dawntrail changes, and that worked completely fine. I wonder what changed to make that happen.

**Comment by jessy5765** [comment]
To continue on this, glad I found this thread, **No Tank You** is another one that will cause them to stop working. Wild... sadly its not stackable.
