### ISSUE TITLE
Crash report on linked Mare User

### ISSUE THREAD

**Issue by NevendyND** [kawaii/Moodles#4]
This is a Report from a Friend, she can't create an own Github atm so she asked me if i can create it for her.

"A Friend used the Plugin to put a Buff on me, then i crashed, this also happed when he casted this Buff on himself via Timer."

Log of the first Crash when he put that Buff on her.
[dalamud_appcrash_20240301_163414_174_28748.log](https://github.com/kawaii/Moodles/files/14463112/dalamud_appcrash_20240301_163414_174_28748.log)

![maXD8t69et](https://github.com/kawaii/Moodles/assets/28860034/2725334e-2475-44fd-8b6a-fa014844c3f6)

Added
You can put buffs on other Players that are not linked, but can't remove it from them after adding it to them.
It only could be removed after closing Game.

**Comment by kawaii** [comment]
Gonna close this one too as it's probably semi-related to your other crash and the Mare stuff is being worked on anyway.
