### ISSUE TITLE
unable to find certain statuses

### ISSUE THREAD

**Issue by carter-valentine** [kawaii/Moodles#45]
Hi there, love the plugin. I have been scouring the sheet for the detrimental debuff "Temporal Displacement" from TEA (also A12) and have been unable to find it. I had multiple other friends try and find it to no avail and it seems like there's certain statuses we're unable to find. Is this something I can do to fix on my end or is it something deeper.

**Comment by Glyceri** [comment]
Hi!
Some statuses appear like a status but aren't actually a status and thus cannot be used unfortunately.
Think for example of the mounted status. It's not actually a status but appears like one.
For the mechanic you are describing this approach makes sense.
