### ISSUE TITLE
Color Glow Change

### ISSUE THREAD

**Issue by PrincessJaade** [kawaii/Moodles#46]
Hello! Not really an issue (maybe a skill issue lol) more of a "how to" inquiry. Ive been trying to add color/glow to my text and cant figure out the proper format on how to do it. Would greatly appreciate if you could help! Ty! ^-^

**Comment by Glyceri** [comment]
Sorry it took me this long to respond, I couldn't figure out how to do it initially but now I can. You can use the` [color=...]Text Here[/color]` format same goes for `[glow]Text Here[/glow]` `[i]This will be slanted[/i]`
