### ISSUE TITLE
Plugin causes game to hang on startup

### ISSUE THREAD

**Issue by joker-119** [kawaii/Moodles#47]
Firstly - I will preface this by saying hello, I am the dreaded linux user every dev fears.

Am unsure why, how how I can help debug it, but while I can install your plugin and use it fine, if the plugin is installed when first launching the game, the game will hang (sometimes for 1-2mins, sometimes indefinitely) when the opening dawntrail logo begins to render.

Sound appears to still work, but graphics and the rest of the app are frozen.

Removing this plugin solves the problem upon re-launching the game.

Problem exists both with and without other plugins present.

**Comment by Glyceri** [comment]
Hello! Thank you for reaching out.
I'm Glyceri, temporary (hopefully) maintainer of Moodles.

Could you provide me with your log files?
I don't exactly know how to get to them on Linux but on windows it would be %AppData%/XIVLauncher/dalamud.log 
Basically its the location where the XIVLauncher is installed.
After you launch the game and have had the hang you can close the game again. The log file should contain all the relevant information we need.

_If you don't want to send the file in public over Github you can send it to me on Discord 'glyceri'._
