### ISSUE TITLE
Moodles can't find icon ids (Probably known?)

### ISSUE THREAD

**Issue by Maxunit** [kawaii/Moodles#49]
Just updated moodles and i am just filling a report here that no moodles are working, since moodles fails to find the given icons and id's with the following error.
![image](https://github.com/user-attachments/assets/9a282e45-03e0-4d48-968c-20177242e7b1)
but that might be a known issue? Reporting anyways, just in case

EDIT: Oh okay, the icons just shifted, it seems and that old moodles are no longer working?

EDIT 2: Okay, just searching for the old Icon ID shows the icon and the new ID. Phew...

**Comment by Luggs123** [comment]
Yes, it appears that buff icons (at least, those I've been using) have added a leading "2" in their icon IDs.

**Comment by Glyceri** [comment]
This should be fixed in update 1.0.0.29
