### ISSUE TITLE
Suggestion: add a command to remove all Moodles on a character.

### ISSUE THREAD

**Issue by Luggs123** [kawaii/Moodles#51]
I tend to use one of several Moodles at a given time when I take different appearances, and I have a "revert" macro for when I return to my default appearance. However, as the plugin currently acts, this revert macro must individually remove all Moodles, as it does not know which appearance I was in (and therefore which Moodle I had) upon execution. This causes scaling issues, as the number of Moodles I'll have to remove increases with each appearance I devise. This may eventually break the macro line cap.

I suggest adding a command to remove all Moodles at once. Anyone using one of multiple options would benefit, and even those who want to maintain a constant Moodle can use the current workflow or re-enable their desired Moodles within the same macro (assuming they fit within the line limit).

**Comment by Glyceri** [comment]
W idea, adding that!
It would follow the same command structure as all the other commands:
/moodle remove target moodle|preset **all**

**Comment by Glyceri** [comment]
The all selector should now work for remove, add, toggle on moodles and presets as of update 1.0.0.30
