### ISSUE TITLE
Debuff VFX appearing offset from character

### ISSUE THREAD

**Issue by EminentEmily** [kawaii/Moodles#52]
When I apply a debuff moodle, it appears about 5 yalms in front of my character rather than on it.
![image](https://github.com/user-attachments/assets/7b753a11-a809-40ee-8d3d-dff9325ed43d)

**Comment by Glyceri** [comment]
Are you perhaps using Heels or any other plugin that can offset your location from the default game?

**Comment by Glyceri** [comment]
Tentatively fixes as of 1.0.0.32

**Comment by EminentEmily** [comment]
Hey there. Apologies, I didn't see the notification about your response. So it does appear to be related to using custom body models. I turned off all Penumbra mods and it applies correctly. So is this something that should be sent to the maker of the body mod? Or is there a way to offset where effects appear?

**Comment by Glyceri** [comment]
There's nothing I can do about that sadly. If some other mod breaks the location of VFX it is out of my control to get it at the right location.
