### ISSUE TITLE
Errors in console.

### ISSUE THREAD

**Issue by auxqii** [kawaii/Moodles#54]
Hello. I would like some assistance with those errors that pop. 
![moodleserror](https://github.com/user-attachments/assets/fdcdb27c-ff19-4c3f-a690-8e46382c45b2)

Plugins that I use that affect UI ; Aetherment , BigPlayerDebuffs , EnemyListDebuffs, EnemyListHP, Party Icons.

**Comment by Glyceri** [comment]
I admit, I have no idea what this means. Time to asm around!

**Comment by Glyceri** [comment]
Weeeiiirrdd, moodles shouldnt show in Duties

**Comment by auxqii** [comment]
I can see a new update on moodles right now.

**Comment by Glyceri** [comment]
Yepp, this one should fix another error that _might_ have influenced this one

**Comment by auxqii** [comment]
Alright. I will check it out 💯

**Comment by auxqii** [comment]
![image](https://github.com/user-attachments/assets/cf467ea3-6da7-41ed-a169-6522262a1249)

What about this one?

**Comment by Glyceri** [comment]
Take over moodles he said [**:catkiss:**](https://tenor.com/en-GB/view/kiss-gif-11816971814746635421) It'll be fun he said [**:catkiss:**](https://tenor.com/en-GB/view/kiss-gif-11816971814746635421)
_Istg... Kite wrote not a single line of (null) safety into Moodles. **I'm going to lose it.**_

**Is IPC so people can send w/e they like so who knows if this will ever resolve properly:**
`[EzIPC("ClearStatusManagerByPtr")]
private void ClearStatusManager(nint ptr) `

**Can literally be null:** 
`Svc.Objects.CreateObjectReference(ptr)`
_(It literally returns an [`IGameObject?`](https://github.com/goatcorp/Dalamud/blob/dd26d82117d7496777377b2fade57ac87af4e2e4/Dalamud/Plugin/Services/IObjectTable.cs#L55))_

**Can fail to cast in cases where the given object is null OR JUST NOT A PLAYER?????:**
`(IPlayerCharacter)Svc.Objects.CreateObjectReference(ptr)`

**Literally doesn't check if the player is null, valid or exists and just grabs the status manager:**
`void ClearStatusManager(IPlayerCharacter pc)
{
    var m = pc.GetMyStatusManager(); ...`
_(You can't assume pc is null if you don't use nullability OR check for null in the method that calls this one out of safety!!!)_

```
[EzIPC("ClearStatusManagerByPtr")]
private void ClearStatusManager(nint ptr) => ClearStatusManager((IPlayerCharacter)Svc.Objects.CreateObjectReference(ptr));

[EzIPC("ClearStatusManagerByPC")]
private void ClearStatusManager(IPlayerCharacter pc)
{
    var m = pc.GetMyStatusManager();
    foreach(var s in m.Statuses)
    {
        if(!s.Persistent)
        {
            m.Cancel(s);
        }
    }
    m.Ephemeral = false;
}

**Comment by auxqii** [comment]
I have no clue what you've just said but thank you and your similars for making this game a better , more enjoyable place for everyone <3

**Comment by auxqii** [comment]
Alright, thank you for that.

**Comment by Glyceri** [comment]
akshually, turns out this is not reliably fixed... somehow...
Also depends on what plogon is throwing errors

**Comment by auxqii** [comment]
It was Sonar plugin.

**Comment by Glyceri** [comment]
Then we cannot help 😔

**Comment by auxqii** [comment]
Yeah I know. The errors regarding moodles have stopped so far
