### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by TatsuruIKR** [kawaii/Moodles#8]
Unfortunately I can't tell what actually triggered this crash, since all I was doing at the time was summoning my carbuncle (as SMN) but the crash log says it's from the Moodles routine. This buff was active at the time.

![image](https://github.com/kawaii/Moodles/assets/44866610/91263dcc-ddba-4012-9532-bf46c65c3220)
[dalamud_appcrash_20240301_133117_299_19924.log](https://github.com/kawaii/Moodles/files/14464017/dalamud_appcrash_20240301_133117_299_19924.log)

**Comment by kawaii** [comment]
Thanks for the report, will look into it.

**Comment by TatsuruIKR** [comment]
The tspack:
[crash-20240301133152.zip](https://github.com/kawaii/Moodles/files/14464182/crash-20240301133152.zip)

**Comment by kawaii** [comment]
Hmm, doesn't seem to contain all the needed information. Can you replicate the crash and upload your `dalamud.log` file before starting the game again please?

**Comment by kawaii** [comment]
Can I have a screenshot of your party list? With your carbuncle summoned?
You can blur your character name out if you wish.

Are you using any other plugins that modify the party list such as Job Bars?

**Comment by TatsuruIKR** [comment]
I use the in-game option to hide my own name if I'm not in a party. None of the plugins I use affect the party list as far as I'm aware.

![image](https://github.com/kawaii/Moodles/assets/44866610/b6c47865-7d19-48a7-bd46-786742f50fd5)
![image](https://github.com/kawaii/Moodles/assets/44866610/9a07f047-9312-48f2-9e59-b7213fe94905)

**Comment by kawaii** [comment]
Right I see, I didn't account for this at all. Moodles is trying to apply to an element that doesn't exist since you aren't in it.
To stop the crashing for now you'll need to enable the party list while solo until I can push out a fix for this.

Thanks for the report.

**Comment by TatsuruIKR** [comment]
No problem! Glad to have helped.

**Comment by kawaii** [comment]
Hi, this should be resolved in 1.0.0.9. (4f3ea31fe9d54b05674422f48085db78076263a4)
