### ISSUE TITLE
Opt-In for Mare

### ISSUE THREAD

**Issue by Sp00kems** [kawaii/Moodles#9]
A couple friends and I think it would be nice to have an optional sort of toggle to enable the use of Moodles on other players when Individually Sync'd with them using Mare. It has a lot of potential in the Roleplay scene as well as simply messing with friends. #

**Comment by kawaii** [comment]
I plan on adding a whitelist system eventually where you can list the names of players who are allowed to apply Moodles to your own StatusManager, but it will take some time to implement.

**Comment by Sp00kems** [comment]
That sounds awesome! I look forward to it!
